### PR TITLE
Fix #5: issues with SWE, Waterfall Restock, and avalanche

### LINKED ISSUE #5: Some engine bugs with SWE and Waterfall Restock
(Tested by setting external to 0% and with both SWE and Waterfall Restock together) Engines that don't have their Waterfall/Stock sounds removed are: All jet engines except Rapier when in closed cycle mode, All SRBs, Spark, Vector, Skiff, Skipper, Mammoth, and Rhino. It seems that the last 6 engines are listed in the WaterfallRestock_overrides in StockWaterfallEffects\Mod Configurations\ReStock, it can probably be fixed by making a config for it. As for the Jet engines and the SRBs, I have no idea.

### PR DESCRIPTION
**Pull request by likeproblem**
I added avalanche plumes, and restock waterfall expansion support
Also fixed StockWaterfallEffects which were not complete

Readme *should* be also updated to include these new two mods

My first PR on github, so might contain some errors here and there

### CODE REVIEW

**Comment by likeproblem** [comment]
Thanks for the fixes! Also, what is the difference between , and &? I have read what it has different priority than other logical operators, is that correct?

**Comment by JonnyOThan** [comment]
> Also, what is the difference between , and &? I have read what it has different priority than other logical operators, is that correct?

They are the same, but I like to be explicit.  Likewise changing `PART[*]` to `PART` also probably has no effect (the former would not apply to a part without a name, but that's practically never an issue) - but there's no point in the `[*]` filter either.

**Comment by JonnyOThan** [comment]
Oh and I renamed the file back just so that it keeps the diff sane.

**Comment by likeproblem** [comment]
Also README needs to be changed to account for these two mods

**Pull request merged**
